/*USE [master]
GO
/****** Object:  Database [DriveImage]    Script Date: 4/29/2026 2:26:23 PM ******/
CREATE DATABASE [DriveImage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DriveImage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DriveImage.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DriveImage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DriveImage_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DriveImage] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DriveImage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DriveImage] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DriveImage] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DriveImage] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DriveImage] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DriveImage] SET ARITHABORT OFF 
GO
ALTER DATABASE [DriveImage] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DriveImage] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DriveImage] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DriveImage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DriveImage] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DriveImage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DriveImage] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DriveImage] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DriveImage] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DriveImage] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DriveImage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DriveImage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DriveImage] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DriveImage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DriveImage] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DriveImage] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DriveImage] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DriveImage] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DriveImage] SET  MULTI_USER 
GO
ALTER DATABASE [DriveImage] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DriveImage] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DriveImage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DriveImage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DriveImage] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DriveImage] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DriveImage] SET QUERY_STORE = ON
GO
ALTER DATABASE [DriveImage] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DriveImage]
GO
/****** Object:  Table [dbo].[Images]    Script Date: 4/29/2026 2:26:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Images](
	[imageID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NULL,
	[imagePath] [varchar](255) NULL,
	[uploadDate] [datetime] NULL,
	[description] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[imageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 4/29/2026 2:26:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[password] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Images]  WITH CHECK ADD FOREIGN KEY([userID])
REFERENCES [dbo].[Users] ([userID])
GO
USE [master]
GO
ALTER DATABASE [DriveImage] SET  READ_WRITE 
GO
*/
INSERT INTO Users (UserID, username, password)
VALUES (1 , N'PhucQuynh', '123456');